In [6]:
import sklearn
import numpy as np
import pandas as pd

In [241]:
feature_train_before = {}
feature_vina_score = {}

with open('/mnt/processed_data/feature_test.txt','r') as fi:
    feature_trainlist =  [l[:-1] for l in fi if l.strip()]
    for rfpair_ in feature_trainlist:
        rfpair = rfpair_.split(',')
        feature_train_before[rfpair[0]]=rfpair_
with open('/mnt/processed_data/vina_feature_test.txt','r') as fi:
    vina_score_list =  [l[:-1] for l in fi if l.strip()]
    for groundtruthpair in vina_score_list:
        groundtruthpair = groundtruthpair.split(' ')
        feature_vina_score[str(groundtruthpair[0])] = groundtruthpair[1]

In [242]:
total_feature = {}
for prot in feature_train_before.keys():
    if prot not in feature_vina_score.keys():
        continue
    total_feature[prot] = feature_train_before[prot]+','+feature_vina_score[prot]
output_file = '/mnt/processed_data/full_feature_test.txt'
with open(output_file,'w') as fo:
    for protein in total_feature.keys():
        fo.write(total_feature[protein]+'\n')

In [243]:
feature_train_before = {}
feature_vina_score = {}

with open('/mnt/processed_data/feature_train.txt','r') as fi:
    feature_trainlist =  [l[:-1] for l in fi if l.strip()]
    for rfpair_ in feature_trainlist:
        rfpair = rfpair_.split(',')
        feature_train_before[rfpair[0]]=rfpair_
with open('/mnt/processed_data/vina_feature_train.txt','r') as fi:
    vina_score_list =  [l[:-1] for l in fi if l.strip()]
    for groundtruthpair in vina_score_list:
        groundtruthpair = groundtruthpair.split(' ')
        feature_vina_score[str(groundtruthpair[0])] = groundtruthpair[1]

In [244]:
total_feature = {}
for prot in feature_train_before.keys():
    if prot not in feature_vina_score.keys():
        continue
    total_feature[prot] = feature_train_before[prot]+','+feature_vina_score[prot]
output_file = '/mnt/processed_data/full_feature_train.txt'
with open(output_file,'w') as fo:
    for protein in total_feature.keys():
        fo.write(total_feature[protein]+'\n')

In [324]:
df_train = pd.read_csv('/mnt/processed_data/full_feature_train.txt',header=None)

In [325]:
df_train

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,4i7p,0,0.000000,10,2.322000,10,3.153000,11,3.542727,11,...,0.0000,0.0000,0.0000,0.0000,49.5684,81.4142,0.0000,0.0000,42.1848,173.1674
1,1oif,0,0.000000,9,2.231111,9,3.081111,3,3.570000,3,...,18.7256,27.7664,77.8306,14.2067,25.9804,48.0422,11.8186,146.4116,0.0000,370.7821
2,5k8s,0,0.000000,14,2.286429,14,3.120000,1,3.620000,1,...,0.0000,65.1065,68.8260,0.0000,62.7575,114.7110,0.0000,96.7423,0.0000,408.1433
3,2w47,0,0.000000,5,2.452000,5,3.312000,2,3.405000,2,...,4.9013,70.8950,70.8823,12.4490,149.6361,18.7129,25.7225,107.3611,0.0000,460.5602
4,5ha1,8,3.780000,2,2.080000,2,2.905000,0,0.000000,0,...,44.5546,0.0000,0.0000,0.0000,0.0000,0.0000,451.2051,38.3055,0.0000,534.0652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3597,4km0,10,3.738000,35,2.667143,35,3.380286,11,3.563636,11,...,0.0000,14.1186,79.8743,1.0367,98.3460,145.6607,161.2867,12.5675,58.9842,571.8747
3598,2oi2,0,0.000000,5,2.178000,5,3.006000,2,3.350000,2,...,12.6596,175.2907,39.4744,15.3597,69.2143,0.0000,191.2388,108.2044,0.0000,611.4419
3599,6chp,6,3.740000,23,2.473478,23,3.276522,11,3.402727,11,...,110.1553,3.7160,17.3067,30.2428,186.1265,196.6199,296.4844,208.6771,0.0000,1049.3287
3600,5lvl,4,3.685000,4,2.305000,4,3.102500,2,3.675000,2,...,1.6424,1.6974,7.1959,26.0241,99.2294,267.4901,130.2385,45.8159,0.0000,579.3337
3601,3uzj,6,3.736667,11,2.628182,11,3.444545,9,3.526667,9,...,0.0000,6.6001,0.0068,29.6253,66.1604,175.7527,47.9810,9.1443,0.0000,335.2706

In [392]:
ground_truth_train = df_train[17] + df_train[18]
ground_truth_train

0        3.50
1        7.72
2        8.22
3        4.98
4        7.19
        ...
3597     6.04
3598     6.30
3599    10.12
3600     5.90
3601     5.55
Length: 3602, dtype: float64

In [362]:
feature_train = df_train[list(df.columns[1:39])]
feature_train = feature_train.drop(columns=[17])
feature_train

,1,2,3,4,5,6,7,8,9,10,...,29,30,31,32,33,34,35,36,37,38
0,0,0.000000,10,2.322000,10,3.153000,11,3.542727,11,3.448182,...,0.0000,0.0000,0.0000,0.0000,49.5684,81.4142,0.0000,0.0000,42.1848,173.1674
1,0,0.000000,9,2.231111,9,3.081111,3,3.570000,3,3.706667,...,18.7256,27.7664,77.8306,14.2067,25.9804,48.0422,11.8186,146.4116,0.0000,370.7821
2,0,0.000000,14,2.286429,14,3.120000,1,3.620000,1,2.780000,...,0.0000,65.1065,68.8260,0.0000,62.7575,114.7110,0.0000,96.7423,0.0000,408.1433
3,0,0.000000,5,2.452000,5,3.312000,2,3.405000,2,3.910000,...,4.9013,70.8950,70.8823,12.4490,149.6361,18.7129,25.7225,107.3611,0.0000,460.5602
4,8,3.780000,2,2.080000,2,2.905000,0,0.000000,0,0.000000,...,44.5546,0.0000,0.0000,0.0000,0.0000,0.0000,451.2051,38.3055,0.0000,534.0652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3597,10,3.738000,35,2.667143,35,3.380286,11,3.563636,11,3.192727,...,0.0000,14.1186,79.8743,1.0367,98.3460,145.6607,161.2867,12.5675,58.9842,571.8747
3598,0,0.000000,5,2.178000,5,3.006000,2,3.350000,2,3.040000,...,12.6596,175.2907,39.4744,15.3597,69.2143,0.0000,191.2388,108.2044,0.0000,611.4419
3599,6,3.740000,23,2.473478,23,3.276522,11,3.402727,11,3.269091,...,110.1553,3.7160,17.3067,30.2428,186.1265,196.6199,296.4844,208.6771,0.0000,1049.3287
3600,4,3.685000,4,2.305000,4,3.102500,2,3.675000,2,3.395000,...,1.6424,1.6974,7.1959,26.0241,99.2294,267.4901,130.2385,45.8159,0.0000,579.3337
3601,6,3.736667,11,2.628182,11,3.444545,9,3.526667,9,3.030000,...,0.0000,6.6001,0.0068,29.6253,66.1604,175.7527,47.9810,9.1443,0.0000,335.2706

In [344]:
for i in range(7):
    feature_train[39+i] = feature_train[i*2+1]*feature_train[i*2+2]
feature_train_enhance = feature_train
feature_train_enhance

0       2.293359
1       4.747976
2       7.585915
3       4.567105
4       6.453905
          ...
3597    5.652626
3598    3.007294
3599    7.705980
3600    5.834451
3601    3.957047
Name: 18, Length: 3602, dtype: float64

In [363]:
feature_train_final = feature_train_enhance[[i for i in range(18, 46)]]
feature_train_final

,18,19,20,21,22,23,24,25,26,27,...,36,37,38,39,40,41,42,43,44,45
0,2.293359,-6.548606,-0.056838,0.0,6.0,0.0,1.0,-0.008648,-0.000000,0.0,...,0.0000,42.1848,173.1674,0.00,23.22,31.53,38.97,37.93,65.37,0.00
1,4.747976,-12.325639,-0.178950,2.5,10.0,2.5,1.0,-0.043782,-7.415826,4.0,...,146.4116,0.0000,370.7821,0.00,20.08,27.73,10.71,11.12,0.00,0.00
2,7.585915,-34.267765,-0.704370,2.0,22.0,2.0,0.0,-0.141476,-5.642438,4.0,...,96.7423,0.0000,408.1433,0.00,32.01,43.68,3.62,2.78,9.85,4.01
3,4.567105,-15.850066,-0.989427,6.5,24.0,6.5,1.0,-0.218206,-9.119599,6.0,...,107.3611,0.0000,460.5602,0.00,12.26,16.56,6.81,7.82,3.52,0.00
4,6.453905,19.504673,0.072814,5.5,21.0,5.5,19.0,0.011861,-0.692759,8.0,...,38.3055,0.0000,534.0652,30.24,4.16,5.81,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3597,5.652626,-3.000091,0.137236,3.0,17.0,3.0,9.0,0.025467,-3.682751,2.0,...,12.5675,58.9842,571.8747,37.38,93.35,118.31,39.20,35.12,25.79,0.00
3598,3.007294,-33.841424,-1.543116,8.5,18.0,8.5,3.0,-0.279027,-7.449647,8.0,...,108.2044,0.0000,611.4419,0.00,10.89,15.03,6.70,6.08,8.70,0.00
3599,7.705980,-12.741176,0.164793,7.0,32.0,6.0,14.0,0.025782,-3.714811,8.0,...,208.6771,0.0000,1049.3287,22.44,56.89,75.36,37.43,35.96,39.69,0.00
3600,5.834451,-1.920548,-0.046899,0.0,17.0,0.0,11.0,-0.012682,-0.452615,0.0,...,45.8159,0.0000,579.3337,14.74,9.22,12.41,7.35,6.79,0.00,0.00
3601,3.957047,-1.132421,-0.101999,0.0,9.0,0.0,4.0,-0.029648,-1.162582,0.0,...,9.1443,0.0000,335.2706,22.42,28.91,37.89,31.74,27.27,21.98,4.32

In [286]:
deltavinarf_train = df_train[list(df.columns[18:39])]
deltavinarf_train

,18,19,20,21,22,23,24,25,26,27,...,29,30,31,32,33,34,35,36,37,38
0,2.293359,-6.548606,-0.056838,0.0,6.0,0.0,1.0,-0.008648,-0.000000,0.0,...,0.0000,0.0000,0.0000,0.0000,49.5684,81.4142,0.0000,0.0000,42.1848,173.1674
1,4.747976,-12.325639,-0.178950,2.5,10.0,2.5,1.0,-0.043782,-7.415826,4.0,...,18.7256,27.7664,77.8306,14.2067,25.9804,48.0422,11.8186,146.4116,0.0000,370.7821
2,7.585915,-34.267765,-0.704370,2.0,22.0,2.0,0.0,-0.141476,-5.642438,4.0,...,0.0000,65.1065,68.8260,0.0000,62.7575,114.7110,0.0000,96.7423,0.0000,408.1433
3,4.567105,-15.850066,-0.989427,6.5,24.0,6.5,1.0,-0.218206,-9.119599,6.0,...,4.9013,70.8950,70.8823,12.4490,149.6361,18.7129,25.7225,107.3611,0.0000,460.5602
4,6.453905,19.504673,0.072814,5.5,21.0,5.5,19.0,0.011861,-0.692759,8.0,...,44.5546,0.0000,0.0000,0.0000,0.0000,0.0000,451.2051,38.3055,0.0000,534.0652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3597,5.652626,-3.000091,0.137236,3.0,17.0,3.0,9.0,0.025467,-3.682751,2.0,...,0.0000,14.1186,79.8743,1.0367,98.3460,145.6607,161.2867,12.5675,58.9842,571.8747
3598,3.007294,-33.841424,-1.543116,8.5,18.0,8.5,3.0,-0.279027,-7.449647,8.0,...,12.6596,175.2907,39.4744,15.3597,69.2143,0.0000,191.2388,108.2044,0.0000,611.4419
3599,7.705980,-12.741176,0.164793,7.0,32.0,6.0,14.0,0.025782,-3.714811,8.0,...,110.1553,3.7160,17.3067,30.2428,186.1265,196.6199,296.4844,208.6771,0.0000,1049.3287
3600,5.834451,-1.920548,-0.046899,0.0,17.0,0.0,11.0,-0.012682,-0.452615,0.0,...,1.6424,1.6974,7.1959,26.0241,99.2294,267.4901,130.2385,45.8159,0.0000,579.3337
3601,3.957047,-1.132421,-0.101999,0.0,9.0,0.0,4.0,-0.029648,-1.162582,0.0,...,0.0000,6.6001,0.0068,29.6253,66.1604,175.7527,47.9810,9.1443,0.0000,335.2706

In [249]:
df_test = pd.read_csv('/mnt/processed_data/full_feature_test.txt',header=None)
df_test

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,3gy4,1,3.880000,25,2.464400,25,3.237200,12,3.449167,12,...,39.0406,7.5221,84.7953,13.1382,44.4557,114.0752,17.4523,69.0016,0.0000,389.4810
1,3ui7,7,3.728571,4,1.952500,4,2.882500,1,3.910000,1,...,0.0000,0.0000,23.7470,44.9719,74.9212,188.3221,245.2182,154.5457,0.0000,731.7261
2,3fv2,6,3.635000,44,2.471136,44,3.207500,23,3.350435,23,...,35.4898,112.4987,77.7396,14.3181,17.2618,26.5768,98.4570,206.2443,0.0000,588.5861
3,2qbq,2,3.795000,8,2.732500,8,3.355000,5,3.012000,5,...,32.8945,66.5390,12.6148,37.1787,58.0085,171.7310,224.8436,147.4699,3.1386,754.4186
4,2yge,5,3.752000,5,2.626000,5,3.288000,10,3.616000,10,...,15.8824,35.1752,7.0031,112.7368,142.8347,17.9721,362.1744,219.6009,0.0000,913.3796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,4e5w,6,3.726667,4,1.977500,4,2.955000,2,3.290000,2,...,28.0566,36.4715,0.0000,34.8400,136.4480,175.9554,285.4032,188.7319,0.0000,885.9066
259,4ciw,2,3.730000,11,2.391818,11,3.077273,5,3.188000,5,...,10.8850,54.2789,107.5365,23.2153,18.4876,32.3841,121.0869,117.9216,0.0000,485.7959
260,3rsx,5,3.790000,1,1.890000,1,2.780000,0,0.000000,0,...,0.0000,16.9776,59.2914,8.6572,61.3514,249.5495,48.2745,35.4160,0.0000,479.5176
261,4k77,4,3.525000,4,1.897500,4,2.867500,4,2.865000,4,...,0.6122,18.2004,4.7138,27.3057,96.6275,153.3115,266.0951,75.5406,0.0000,642.4068
262,5aba,5,3.848000,0,0.000000,0,0.000000,2,2.940000,2,...,0.0000,0.8499,45.2071,2.8870,46.6010,97.9082,76.1674,123.9851,76.2412,469.8469

In [391]:
ground_truth_test = df_test[17] + df_test[18]
ground_truth_test

0      5.10
1      9.00
2      8.11
3      7.44
4      5.06
       ...
258    7.66
259    4.82
260    4.41
261    6.63
262    2.98
Length: 263, dtype: float64

In [364]:
feature_test = df_test[list(df.columns[1:39])]
feature_test = feature_test.drop(columns=[17])
feature_test

,1,2,3,4,5,6,7,8,9,10,...,29,30,31,32,33,34,35,36,37,38
0,1,3.880000,25,2.464400,25,3.237200,12,3.449167,12,3.384167,...,39.0406,7.5221,84.7953,13.1382,44.4557,114.0752,17.4523,69.0016,0.0000,389.4810
1,7,3.728571,4,1.952500,4,2.882500,1,3.910000,1,2.690000,...,0.0000,0.0000,23.7470,44.9719,74.9212,188.3221,245.2182,154.5457,0.0000,731.7261
2,6,3.635000,44,2.471136,44,3.207500,23,3.350435,23,3.236522,...,35.4898,112.4987,77.7396,14.3181,17.2618,26.5768,98.4570,206.2443,0.0000,588.5861
3,2,3.795000,8,2.732500,8,3.355000,5,3.012000,5,3.238000,...,32.8945,66.5390,12.6148,37.1787,58.0085,171.7310,224.8436,147.4699,3.1386,754.4186
4,5,3.752000,5,2.626000,5,3.288000,10,3.616000,10,3.352000,...,15.8824,35.1752,7.0031,112.7368,142.8347,17.9721,362.1744,219.6009,0.0000,913.3796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,6,3.726667,4,1.977500,4,2.955000,2,3.290000,2,3.100000,...,28.0566,36.4715,0.0000,34.8400,136.4480,175.9554,285.4032,188.7319,0.0000,885.9066
259,2,3.730000,11,2.391818,11,3.077273,5,3.188000,5,3.060000,...,10.8850,54.2789,107.5365,23.2153,18.4876,32.3841,121.0869,117.9216,0.0000,485.7959
260,5,3.790000,1,1.890000,1,2.780000,0,0.000000,0,0.000000,...,0.0000,16.9776,59.2914,8.6572,61.3514,249.5495,48.2745,35.4160,0.0000,479.5176
261,4,3.525000,4,1.897500,4,2.867500,4,2.865000,4,3.335000,...,0.6122,18.2004,4.7138,27.3057,96.6275,153.3115,266.0951,75.5406,0.0000,642.4068
262,5,3.848000,0,0.000000,0,0.000000,2,2.940000,2,3.025000,...,0.0000,0.8499,45.2071,2.8870,46.6010,97.9082,76.1674,123.9851,76.2412,469.8469

In [365]:
for i in range(8):
    feature_test[39+i] = feature_test[i*2+1]*feature_test[i*2+2]
feature_test_enhance = feature_test
feature_test_enhance

,1,2,3,4,5,6,7,8,9,10,...,37,38,39,40,41,42,43,44,45,46
0,1,3.880000,25,2.464400,25,3.237200,12,3.449167,12,3.384167,...,0.0000,389.4810,3.88,61.61,80.93,41.39,40.61,10.27,0.00,0.0
1,7,3.728571,4,1.952500,4,2.882500,1,3.910000,1,2.690000,...,0.0000,731.7261,26.10,7.81,11.53,3.91,2.69,0.00,2.45,0.0
2,6,3.635000,44,2.471136,44,3.207500,23,3.350435,23,3.236522,...,0.0000,588.5861,21.81,108.73,141.13,77.06,74.44,28.41,0.00,0.0
3,2,3.795000,8,2.732500,8,3.355000,5,3.012000,5,3.238000,...,3.1386,754.4186,7.59,21.86,26.84,15.06,16.19,7.00,0.00,0.0
4,5,3.752000,5,2.626000,5,3.288000,10,3.616000,10,3.352000,...,0.0000,913.3796,18.76,13.13,16.44,36.16,33.52,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,6,3.726667,4,1.977500,4,2.955000,2,3.290000,2,3.100000,...,0.0000,885.9066,22.36,7.91,11.82,6.58,6.20,0.00,0.00,0.0
259,2,3.730000,11,2.391818,11,3.077273,5,3.188000,5,3.060000,...,0.0000,485.7959,7.46,26.31,33.85,15.94,15.30,5.28,0.00,0.0
260,5,3.790000,1,1.890000,1,2.780000,0,0.000000,0,0.000000,...,0.0000,479.5176,18.95,1.89,2.78,0.00,0.00,0.00,0.61,0.0
261,4,3.525000,4,1.897500,4,2.867500,4,2.865000,4,3.335000,...,0.0000,642.4068,14.10,7.59,11.47,11.46,13.34,0.00,0.00,0.0
262,5,3.848000,0,0.000000,0,0.000000,2,2.940000,2,3.025000,...,76.2412,469.8469,19.24,0.00,0.00,5.88,6.05,0.00,0.00,0.0

In [366]:
feature_test_final = feature_test_enhance[[i for i in range(18, 46)]]
feature_test_final

,18,19,20,21,22,23,24,25,26,27,...,36,37,38,39,40,41,42,43,44,45
0,4.245851,-14.721878,-0.646381,2.0,10.0,2.0,5.0,-0.151473,-4.369855,4.0,...,69.0016,0.0000,389.4810,3.88,61.61,80.93,41.39,40.61,10.27,0.00
1,5.825620,-7.154073,0.076496,3.0,24.0,3.0,8.0,0.004900,-1.135112,4.0,...,154.5457,0.0000,731.7261,26.10,7.81,11.53,3.91,2.69,0.00,2.45
2,7.095019,-39.326191,-1.587155,5.5,20.0,5.5,2.0,-0.326315,-10.790929,6.0,...,206.2443,0.0000,588.5861,21.81,108.73,141.13,77.06,74.44,28.41,0.00
3,5.879040,-29.369834,-1.283710,7.0,31.0,7.0,15.0,-0.231042,-4.484096,8.0,...,147.4699,3.1386,754.4186,7.59,21.86,26.84,15.06,16.19,7.00,0.00
4,6.603904,-21.684070,-0.416989,5.5,40.0,5.5,16.0,-0.094488,-2.729984,4.0,...,219.6009,0.0000,913.3796,18.76,13.13,16.44,36.16,33.52,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,7.574627,-24.841311,0.330364,3.0,28.0,3.0,8.0,0.056574,-2.452732,4.0,...,188.7319,0.0000,885.9066,22.36,7.91,11.82,6.58,6.20,0.00,0.00
259,5.524133,-25.630282,-0.921388,5.0,15.0,5.0,4.0,-0.214047,-7.947885,6.0,...,117.9216,0.0000,485.7959,7.46,26.31,33.85,15.94,15.30,5.28,0.00
260,5.059218,-8.890185,-0.314469,1.5,16.0,1.5,9.0,-0.090725,-2.150615,2.0,...,35.4160,0.0000,479.5176,18.95,1.89,2.78,0.00,0.00,0.00,0.61
261,5.547744,-14.787466,-0.121158,2.0,18.0,2.0,7.0,-0.022922,-1.332737,2.0,...,75.5406,0.0000,642.4068,14.10,7.59,11.47,11.46,13.34,0.00,0.00
262,3.804385,-9.756231,0.146199,4.0,23.0,4.0,9.0,0.033242,-0.040452,6.0,...,123.9851,76.2412,469.8469,19.24,0.00,0.00,5.88,6.05,0.00,0.00

In [285]:
deltavinarf_test = df_test[list(df.columns[18:39])]
deltavinarf_test

,18,19,20,21,22,23,24,25,26,27,...,29,30,31,32,33,34,35,36,37,38
0,4.245851,-14.721878,-0.646381,2.0,10.0,2.0,5.0,-0.151473,-4.369855,4.0,...,39.0406,7.5221,84.7953,13.1382,44.4557,114.0752,17.4523,69.0016,0.0000,389.4810
1,5.825620,-7.154073,0.076496,3.0,24.0,3.0,8.0,0.004900,-1.135112,4.0,...,0.0000,0.0000,23.7470,44.9719,74.9212,188.3221,245.2182,154.5457,0.0000,731.7261
2,7.095019,-39.326191,-1.587155,5.5,20.0,5.5,2.0,-0.326315,-10.790929,6.0,...,35.4898,112.4987,77.7396,14.3181,17.2618,26.5768,98.4570,206.2443,0.0000,588.5861
3,5.879040,-29.369834,-1.283710,7.0,31.0,7.0,15.0,-0.231042,-4.484096,8.0,...,32.8945,66.5390,12.6148,37.1787,58.0085,171.7310,224.8436,147.4699,3.1386,754.4186
4,6.603904,-21.684070,-0.416989,5.5,40.0,5.5,16.0,-0.094488,-2.729984,4.0,...,15.8824,35.1752,7.0031,112.7368,142.8347,17.9721,362.1744,219.6009,0.0000,913.3796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,7.574627,-24.841311,0.330364,3.0,28.0,3.0,8.0,0.056574,-2.452732,4.0,...,28.0566,36.4715,0.0000,34.8400,136.4480,175.9554,285.4032,188.7319,0.0000,885.9066
259,5.524133,-25.630282,-0.921388,5.0,15.0,5.0,4.0,-0.214047,-7.947885,6.0,...,10.8850,54.2789,107.5365,23.2153,18.4876,32.3841,121.0869,117.9216,0.0000,485.7959
260,5.059218,-8.890185,-0.314469,1.5,16.0,1.5,9.0,-0.090725,-2.150615,2.0,...,0.0000,16.9776,59.2914,8.6572,61.3514,249.5495,48.2745,35.4160,0.0000,479.5176
261,5.547744,-14.787466,-0.121158,2.0,18.0,2.0,7.0,-0.022922,-1.332737,2.0,...,0.6122,18.2004,4.7138,27.3057,96.6275,153.3115,266.0951,75.5406,0.0000,642.4068
262,3.804385,-9.756231,0.146199,4.0,23.0,4.0,9.0,0.033242,-0.040452,6.0,...,0.0000,0.8499,45.2071,2.8870,46.6010,97.9082,76.1674,123.9851,76.2412,469.8469

In [73]:
deltavinadf = {}
ground_truth = {}
with open('/mnt/processed_data/deltavinarf20_score_train.txt','r') as fi:
    deltavinascore =  [l[:-1] for l in fi if l.strip()]
    for rfpair in deltavinascore:
        rfpair = rfpair.split(',')
        deltavinadf[rfpair[0]]=float(rfpair[1])
with open('/mnt/processed_data/refined-set/index/INDEX_refined_data.2019','r') as fi:
    ground_truth_list =  [l[:-1] for l in fi if l.strip()]
    for groundtruthpair in ground_truth_list:
        groundtruthpair = groundtruthpair.split('  ')
        ground_truth[str(groundtruthpair[0])] = float(groundtruthpair[3])

In [76]:
delta=[]
sse_delta = 0
for prot in deltavinadf.keys():
    tmpdel = ground_truth[prot]-deltavinadf[prot] 
    delta.append(tmpdel)
    sse_delta+=tmpdel**2

sse_delta/len(delta)

3.7748846751804463

In [80]:
deltavinadf = {}
ground_truth = {}
with open('/mnt/processed_data/deltavinarf20_score_test.txt','r') as fi:
    deltavinascore =  [l[:-1] for l in fi if l.strip()]
    for rfpair in deltavinascore:
        rfpair = rfpair.split(' ')
        deltavinadf[rfpair[0]]=float(rfpair[1])
with open('/mnt/processed_data/refined-set/index/INDEX_refined_data.2019','r') as fi:
    ground_truth_list =  [l[:-1] for l in fi if l.strip()]
    for groundtruthpair in ground_truth_list:
        groundtruthpair = groundtruthpair.split('  ')
        ground_truth[str(groundtruthpair[0])] = float(groundtruthpair[3])

In [221]:
delta=[]
sse_delta = 0
for prot in deltavinadf.keys():
    if prot not in ground_truth.keys():
        continue
    tmpdel = ground_truth[prot]-deltavinadf[prot] 
    delta.append(tmpdel)
#     sse_delta+=tmpdel**2

np.sum(np.array(delta)**2)/len(delta)

1.5697361216730037

In [262]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics


# 创建模型并拟合
model = linear_model.LinearRegression()
model.fit(feature_train, ground_truth_train)

# 创建损失计算函数 SSE
def sse(resid):
    return np.sum(resid**2)

# 训练损失和预测损失
resid_train = ground_truth_train - model.predict(feature_train)
sse_train = sse(resid_train)
resid_test = ground_truth_test - model.predict(feature_test)
sse_test = sse(resid_test)
print('train sse:', sse_train/len(ground_truth_train), 'test sse:', sse_test/len(ground_truth_test))

train sse: 2.4026656721568678 test sse: 2.9909597374613006

In [264]:
from sklearn.linear_model import ElasticNetCV
model = ElasticNetCV(l1_ratio=0.5, eps=0.001, n_alphas=100, alphas=None, 
                   fit_intercept=True, normalize=False, precompute="auto", 
                   max_iter=10000, tol=0.00001, cv=5, copy_X=True, verbose=0, 
                   n_jobs=None, positive=False, random_state=None, selection="cyclic")
model.fit(feature_train, ground_truth_train)
resid_train = ground_truth_train - model.predict(feature_train)
sse_train = sse(resid_train)
resid_test = ground_truth_test - model.predict(feature_test)
sse_test = sse(resid_test)
print('train sse:', sse_train/len(ground_truth_train), 'test sse:', sse_test/len(ground_truth_test))

train sse: 2.524231534313436 test sse: 3.119143352740917

/root/anaconda3/envs/vina3/lib/python3.9/site-packages/sklearn/linear_model/_base.py:148: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  warnings.warn(

In [267]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(criterion="squared_error", splitter="best", max_depth=5, 
                            min_samples_split=2, min_samples_leaf=1, 
                            min_weight_fraction_leaf=0.0, max_features=None, 
                            random_state=None, max_leaf_nodes=None, 
                            min_impurity_decrease=0.0)
model.fit(feature_train, ground_truth_train)
resid_train = ground_truth_train - model.predict(feature_train)
sse_train = sse(resid_train)
resid_test = ground_truth_test - model.predict(feature_test)
sse_test = sse(resid_test)
print('train sse:', sse_train/len(ground_truth_train), 'test sse:', sse_test/len(ground_truth_test))

train sse: 1.9959298900843245 test sse: 3.031144527855973

/root/anaconda3/envs/vina3/lib/python3.9/site-packages/sklearn/tree/_classes.py:359: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warnings.warn(

In [291]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=500, criterion='squared_error', max_depth=5, 
                            min_samples_split=2, min_samples_leaf=10, 
                            min_weight_fraction_leaf=0.0, max_features="auto", 
                            max_leaf_nodes=None,  
                            bootstrap=True, oob_score=True, 
                            random_state=None, verbose=0, warm_start=False)
model.fit(deltavinarf_train, ground_truth_train)
resid_train = ground_truth_train - model.predict(deltavinarf_train)
sse_train = sse(resid_train)
resid_test = ground_truth_test - model.predict(deltavinarf_test)
sse_test = sse(resid_test)
print('train sse:', sse_train/len(ground_truth_train), 'test sse:', sse_test/len(ground_truth_test))
# 各特征的重要性
model.feature_importances_

/root/anaconda3/envs/vina3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

train sse: 1.8739303096274345 test sse: 2.686780215758485

array([0.53450409, 0.01108653, 0.02570532, 0.00500178, 0.00417885,
       0.00401068, 0.0410088 , 0.01899402, 0.01173158, 0.00458081,
       0.02511275, 0.00619296, 0.00742445, 0.00951228, 0.02577751,
       0.01023452, 0.02578875, 0.13609744, 0.0074588 , 0.00144941,
       0.08414867])

In [384]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=500, criterion="squared_error", max_depth=7, 
                            min_samples_split=2, min_samples_leaf=10, 
                            min_weight_fraction_leaf=0.0, max_features="auto", 
                            max_leaf_nodes=None,  
                            bootstrap=True, oob_score=True, 
                            random_state=None, verbose=0, warm_start=False)
model.fit(feature_train_final, ground_truth_train)
resid_train = ground_truth_train - model.predict(feature_train_final)
sse_train = sse(resid_train)
resid_test = ground_truth_test - model.predict(feature_test_final)
sse_test = sse(resid_test)
print('train sse:', sse_train/len(ground_truth_train), 'test sse:', sse_test/len(ground_truth_test))
# 各特征的重要性
model.feature_importances_

train sse: 1.4875712105500258 test sse: 2.5623320357292303

array([0.45039249, 0.01462681, 0.02382909, 0.00666043, 0.00688803,
       0.00565241, 0.03305177, 0.017846  , 0.01592342, 0.00625803,
       0.03038934, 0.00953727, 0.01132877, 0.01479198, 0.02964655,
       0.0145071 , 0.02591256, 0.12220878, 0.01178127, 0.00177278,
       0.07043168, 0.01682985, 0.00590697, 0.01026627, 0.01262435,
       0.00826386, 0.01553245, 0.00713969])

In [385]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=500, criterion='squared_error', max_depth=6, 
                            min_samples_split=2, min_samples_leaf=7, 
                            min_weight_fraction_leaf=0.0, max_features="auto", 
                            max_leaf_nodes=None,  
                            bootstrap=True, oob_score=True, 
                            random_state=None, verbose=0, warm_start=False)
model.fit(deltavinarf_train, ground_truth_train)
resid_train = ground_truth_train - model.predict(deltavinarf_train)
sse_train = sse(resid_train)
resid_test = ground_truth_test - model.predict(deltavinarf_test)
sse_test = sse(resid_test)
print('train sse:', sse_train/len(ground_truth_train), 'test sse:', sse_test/len(ground_truth_test))
# 各特征的重要性
model.feature_importances_

train sse: 1.6711932897042037 test sse: 2.626669774706249

array([0.48876046, 0.01555101, 0.02589646, 0.00574219, 0.00719314,
       0.00503109, 0.03765564, 0.02185653, 0.01715626, 0.0063055 ,
       0.03070725, 0.00958165, 0.01234321, 0.01498403, 0.0315463 ,
       0.01536501, 0.02802214, 0.13173304, 0.0127028 , 0.00217959,
       0.0796867 ])